language: java
jdk:
  - oraclejdk6
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9
  - openjdk6
  - openjdk7
  - openjdk8
  - openjdk9

install: true
sudo: false

script: "mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)
