# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: maven
      - name: Publish package
        run: echo ${PUBLISH_KEY} > key.gpg && gpg --import key.gpg && rm -f key.gpg && echo ${MAVEN_SETTINGS} > settings.xml && mvn versions:set -DnewVersion=$(echo ${GITHUB_REF:10}) && mvn --batch-mode deploy --settings settings.xml -Prelease
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_SETTINGS: ${{ secrets.SETTINGS }}
          PUBLISH_KEY: ${{ secrets.GPG_KEY }}
          PUBLISH_ID: ${{ secrets.GPG_ID }}
          PUBLISH_PASS: ${{ secrets.GPG_PASS }}
