# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: maven
      - name: Publish Library
        run: |
          echo "${PUBLISH_KEY}" | base64 -d > key.gpg
          gpg --import key.gpg
          rm -f key.gpg
          echo "${MAVEN_SETTINGS}" | base64 -d > settings.xml
          mvn versions:set -DnewVersion=$(echo ${GITHUB_REF:10})
          mvn deploy --settings settings.xml -Prelease -Dgpg.executable=gpg -Dgpg.keyname="${PUBLISH_ID}" -Dgpg.passphrase="${PUBLISH_PASS}"
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_SETTINGS: ${{ secrets.SETTINGS }}
          PUBLISH_KEY: ${{ secrets.GPG_KEY }}
          PUBLISH_ID: ${{ secrets.GPG_ID }}
          PUBLISH_PASS: ${{ secrets.GPG_PASS }}
