# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: maven
      - name: Configure GPG Key
        run: |
          echo -n "${{ secrets.GPG_KEY }}" | base64 -d | GPG_TTY=$(tty) gpg --import
      - name: Configure settings
        run: |
          echo "${{ secrets.SETTINGS }}" | base64 -d > settings.xml
      - name: Configure Version
        run: |
          mvn versions:set -DnewVersion=$(echo ${GITHUB_REF:10})
      - name: Publish Library
        run: |
          mvn deploy --settings settings.xml -Prelease -Dgpg.executable=gpg -Dgpg.keyname="${{ secrets.GPG_ID }}" -Dgpg.passphrase="${{ secrets.GPG_PASS }}"
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
